apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app-spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mon-app-spring
  template:
    metadata:
      labels:
        app: mon-app-spring
    spec:
      containers:
      - name: mon-app-spring
        image: callme7liwa/app-spring:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mon-app-java-service
spec:
  selector:
    app: mon-app-spring   # Modifié pour correspondre au label utilisé par le déploiement
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
