apiVersion: v1
clusters:
- cluster:
    certificate-authority: home/ca.crt
    extensions:
    - extension:
        last-update: Thu, 04 Apr 2024 16:35:05 CEST
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: cluster_info
    server: https://127.0.0.1:51962
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Thu, 04 Apr 2024 16:35:05 CEST
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: home/client.crt
    client-key: home/client.key
